x = int(input("enter the x value: "))
y = int(input("enter the y value: "))
add = (x + y)
min = (x - y)
mul = (x*y)
rem = (x%y)
ddiv = (x//y)
print(add)
print(min)
print(mul)
print(rem)
print(ddiv)
z = input("enter the text:")
a = input("enter the text:")
cat=(z+a)
print(cat)
